### ISSUE TITLE
Auto-shutdown timeout

### ISSUE THREAD

**Issue by spth** [javl/web-training-collar#1]
AFAIK, the shock unit on such devices has a 4 minute auto-shutdown timeout, allowing the wearer to avoid any shock by not moving for 4 minutes.

However, there is a simple hack to disable it by replacing the tilt switch in the shock unit by an oscillator: https://github.com/spth/cockshock2

Philipp

**Comment by javl** [comment]
I've had my web training collar on a table for 4+ minutes during expos and it still worked, so it seems mine doesn't have this problem? Weird that some models have this timeout, as your dog could also be quietly sleeping for a couple minutes, after which the transmitter wouldn't work anymore?

**Comment by spth** [comment]
Did you move the unit before trying again after the 4+ minutes?

I looked into two different types of these shock collars (their shock units look the same from the outside, but the electronics inside are different, the remote controls look like https://github.com/spth/cockshock/blob/master/doc/remotecontrol.jpeg and https://github.com/spth/cockshock2/blob/master/doc/remotecontrol.jpeg).

Both have the 4 minute auto-shutdown timeout. There is a tilt switch in the shock unit it looks similar to an electrolytic capacitor, but has different marking. If the tilt switch detects no movement for 4 minutes it goes into shutdown. Then the shock unit does not respond to any RF commands. Apparently the tilt switch is connected to an interrupt line, so any time there is movement, the unit comes out of shutdown, and becomes active for 4 minutes (or longer if there is further movement).

I guess this makes sense for dog training. A misbehaving dog would be moving; when the dog is immobile there would be no need to use the shock unit. The auto-shutdown saves a lot of energy; when the shock unit is not used much, the difference in how long the battery lasts is days vs. months. 

Philipp

**Comment by javl** [comment]
I think there is a good change I never noticed the timeout because the device is moved around a lot. Most places I've used the web training collar it would be on the table for a while until someone picked it up to use for a couple of minutes.
But good to know for possible future use of these devices.
